name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ChatterinoUpdater
      run: msbuild -p:Configuration=Release

    - name: tree
      run: |
        tree /F

    - name: Package
      shell: pwsh
      run: |
        mkdir pkg
        cp ./ChatterinoUpdater/ChatterinoUpdater/bin/Release/ChatterinoUpdater.exe ./pkg/
        cp ./ChatterinoUpdater/ChatterinoUpdater/dll/ICSharpCode.SharpZipLib.dll ./pkg/
        cp ./ChatterinoUpdater/ChatterinoUpdater/dll/LICENSE.txt ./pkg/SharpZipLib_LICENSE.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ChatterinoPortableUpdater
        path: pkg/*
